spring:
#  profiles:
#    active: dev
  application:
    name: "food-service"
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices_lcwd?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  config:
    import: "configserver:http://localhost:9096/"
#spring-cloud-bus with amqp property - rabbitmq default username, password and port
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 9092

eureka:
  client:
    register-with-eureka: true  # Should this service register itself? (Yes)
    fetch-registry: true       # Should this service fetch the registry? (Yes)
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  instance:
    hostname: localhost
    prefer-ip-address: false     # Ensures hostname is used instead of IP
#    instance-id: ${spring.application.name}:${server.port}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  info:
#    env:
#      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 60
        wait-duration-in-open-state: 5000ms






