spring:
#  profiles:
#    active: prod
  application:
    name: "food-service"
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_lcwd?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9092

eureka:
  client:
    register-with-eureka: true  # Should this service register itself? (Yes)
    fetch-registry: true       # Should this service fetch the registry? (Yes)
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true



